### ISSUE TITLE
Throttling per apikey (with backpressure)

### ISSUE THREAD

**Issue by beevee** [vostok/airlock.gate#10]
Цель: не допустить деградации сервиса при наличии одного "плохого" клиента, который присылает слишком много данных.

Клиент == апиключ.

Если клиент отправляет слишком много данных, нужно искусственно замедлять обработку запросов от этого конкретного клиента.

**Comment by gnkoshelev** [comment]
Guava seems to me an overkill library.
Also, the RateLimiter.acquire() leads thread to be blocked. I hope this one is not quite what is expected.
