### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by beevee** [vostok/airlock.gate#9]
Гейт не должен терять данные при штатной остановке. Для совместимости с разными окружениями хостинга нужно уметь обрабатывать:

1. Стандартные сигналы UNIX (SIGTERM, SIGQUIT).
2. Специальный HTTP-запрос, который сигнализирует о скором принудительном завершении работы процесса.

**Comment by gnkoshelev** [comment]
The first case would be covered by using of [Shutdown hook](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-).

**Comment by trurl123** [comment]
1-й пункт уже обрабатывается сервисом, можно не делать.
На 2-й создал PR
https://github.com/vostok/airlock.gate/pull/13
